### ISSUE TITLE
Update layout for the documentation site

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-routing#1]
### URL

http://www.kriasoft.com/react-routing

### Source Code

```
/docs/index.html - site layout based on lodash.template
/docs/css/*.css - CSS4 styles based on PostCSS, cssnext
/docs/*.md - site pages (markdown with highlight.js support)
```

### How to Run

```bash
npm start    # starts a lightweight development server, to run the documentation site locally
```

Compilation logic for it is located in `/tools/serve.js`

### To-Do

- [x] Pass current URL and path of the original `.md` file to `index.html` (see [tools/serve.js](https://github.com/kriasoft/react-routing/blob/8de4748b8167d230829fd43c7cda100d6941a23d/tools/serve.js#L50))
- [x] Add side menu for all the inner pages
- [x] Make large header appear only on the home page
- [x] Add Edit on GitHub button on all pages
- [x] Add footer
- [x] Add Disqus comments on inner pages

**Comment by ErrorPro** [comment]
1. done.
2. in progress
